# On each push in 'documentation' branch,
# build documentation and commit the changes
# so that the changes are visible on the website
# https://oca.github.io/OpenUpgrade/

name: Build and commit documentation

on:
  push:
    branches: ["documentation"]

jobs:
  documentation-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out OpenUpgrade Documentation
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Requirements Installation
        run: |
          pip install -r ./requirements.txt
      - name: OpenUpgrade Docs
        run: |
          # try to build the documentation
          sh ./build_openupgrade_docs

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          default_author: github_actions
          message: "[UPD] HTML documentation"
