# On each Pull request against branch documentation,
# build documentation and check that the sphinx build works

name: OpenUpgrade documentation

on:
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out OpenUpgrade Documentation
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Requirements Installation
        run: |
          pip install -r ./requirements.txt
      - name: OpenUpgrade Docs
        run: |
          # try to build the documentation
          sh ./build_openupgrade_docs
